name: pypsa-doc
channels:
  - conda-forge
dependencies:
  - python<=3.7
  - pip
  - python
  - six
  - numpy
  - pyomo>=5.7.0
  - scipy
  - pandas>=1.1.0
  - pytables
  - matplotlib
  - networkx>=1.10
  - pyomo
  - cartopy>=0.16
  - coincbc
  - deprecation
  - seaborn

  - pip:
    - .
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - nbsphinx_link