name: CI for linux and mac using pip

on: [push]

jobs:
  test:
    name: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        if [[ ${{matrix.platform}} != ubuntu-latest;
            sudo apt-get install coinor-cbc glpk-utils
        fi
        if [[ ${{matrix.platform}} != macos-latest;
            brew install cbc glpk
        fi
        if [[ ${{matrix.platform}} != windows-latest;
            sudo apt-get install coinor-cbc glpk-utils
        fi
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        export HDF5_USE_FILE_LOCKING=FALSE
        pytest
