name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install coinor-cbc
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        export HDF5_USE_FILE_LOCKING=FALSE
        pytest



