name: CI

on: [push]

jobs:
  test:
    name: Test on linux and mac using pip
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        if [[ ${{matrix.platform}} != ubuntu-latest;
            sudo apt-get install coinor-cbc glpk-utils
        fi
        if [[ ${{matrix.platform}} != macos-latest;
            brew install cbc glpk
        fi
        if [[ ${{matrix.platform}} != windows-latest;
            sudo apt-get install coinor-cbc glpk-utils
        fi
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Test with pytest
      run: |
        export HDF5_USE_FILE_LOCKING=FALSE
        pytest

    name: Test all plattforms using conda
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.8
    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba
        mamba env create -n pypsa --file=environment.yaml
        mamba env update -n pypsa --file=environment_dev.yaml
        conda activate pypsa
        pip install --no-cache-dir .
    - name: Test with pytest
      run: |
        export HDF5_USE_FILE_LOCKING=FALSE
        pytest



